version: '3.8'

services:
  apache:
    image: httpd:latest
    container_name: apache-server
    ports:
      - "8080:80"
    volumes:
      - ./www:/usr/local/apache2/htdocs/
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Dla prostoty (nie do produkcji!)
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - app-network
    mem_limit: 1g

networks:
  app-network:
    driver: bridge
